// 首页访问量数据
//type:类型   type=1、网站的访问量		type=2  不同语言的访问量
// source：名称
// total:访问量
				


const visitCount={
	"message": "请求成功",
	"code": 200,
	"success": true,
	"data": {
		"totalRows": 999524,
		"resultList": [{
			"type": "1",
			"source": "阿波罗新闻",
			"total": "2541"
		}, {
			"type": "1",
			"source": "倍可亲",
			"total": "2314"
		}, {
			"type": "1",
			"source": "纵览中国",
			"total": "487"
		}, {
			"type": "1",
			"source": "中国慧闻网",
			"total": "769"
		}, {
			"type": "1",
			"source": "新世纪新闻网",
			"total": "443"
		}, {
			"type": "1",
			"source": "中国人权网周刊",
			"total": "470"
		}, {
			"type": "1",
			"source": "明镜译报",
			"total": "189"
		}, {
			"type": "1",
			"source": "万维读者网",
			"total": "166"
		}, {
			"type": "1",
			"source": "中国数字时代",
			"total": "989"
		}, {
			"type": "1",
			"source": "中国瞭望",
			"total": "483"
		}, {
			"type": "1",
			"source": "自由亚洲电台（中文）",
			"total": "2541"
		}, {
			"type": "1",
			"source": "腾讯",
			"total": "703"
		}, {
			"type": "1",
			"source": "明镜",
			"total": "252"
		}, {
			"type": "1",
			"source": "博闻社",
			"total": "633"
		}, {
			"type": "1",
			"source": "多维",
			"total": "354"
		}, {
			"type": "1",
			"source": "参与",
			"total": "520"
		}, {
			"type": "1",
			"source": "新唐人电台",
			"total": "255"
		}, {
			"type": "1",
			"source": "境内社交媒体",
			"total": "488"
		}, {
			"type": "1",
			"source": "境外社交媒体",
			"total": "675"
		}, {
			"type": "1",
			"source": "暗网数据",
			"total": "156"
		}, {
			"type": "1",
			"source": "小众社交工具",
			"total": "187"
		}, {
			"type": "1",
			"source": "网络游戏",
			"total": "224"
		}, {
			"type": "2",
			"source": "英语",
			"total": "887"
		}, {
			"type": "2",
			"source": "藏语",
			"total": "144"
		}, {
			"type": "2",
			"source": "图片",
			"total": "897"
		}, {
			"type": "2",
			"source": "音视频",
			"total": "954"
		}, {
			"type": "2",
			"source": "文本",
			"total": "323"
		}]
	}
}
export default visitCount
